import { userService } from "../../services/User/user.service.local"

import { REMOVE_USER, SET_USER, SET_USERS, UPDATE_USER, ADD_USER } from "../reducers/user.reducer.js"

import { store } from "../store.js"


export async function loadUsers() {
    try {
        const users = await userService.getUsers()
        store.dispatch({ type: SET_USERS, users })
    } catch (err) {
        console.log('UserActions: err in loadUsers', err)
    }
}

export async function removeUser(userId) {
    try {
        await userService.remove(userId)
        store.dispatch({ type: REMOVE_USER, userId })
    } catch (err) {
        console.log('UserActions: err in removeUser', err)
    }
}

export async function saveUser(user) {
    try {
        const type = user._id ? UPDATE_USER : ADD_USER;
        const savedUser = await userService.save(user);
        store.dispatch({ type, user: savedUser });
        return savedUser;
    } catch (err) {
        console.log("Had issues loading users", err);
        throw err;
    }
}

export async function login(credentials) {
    try {
        const user = await userService.login(credentials)
        store.dispatch({
            type: SET_USER,
            user
        })
        return user
    } catch (err) {
        console.log('Cannot login', err)
        throw err
    }
}

export async function signup(credentials) {
    try {
        const user = await userService.signup(credentials)
        store.dispatch({
            type: SET_USER,
            user
        })
        return user
    } catch (err) {
        console.log('Cannot signup', err)
        throw err
    }
}

export async function logout() {
    try {
        await userService.logout()
        store.dispatch({
            type: SET_USER,
            user: null
        })
    } catch (err) {
        console.log('Cannot logout', err)
        throw err
    }
}